---
- name: Deploy Gitea Service
  hosts: tag_docker
  become: true

  pre_tasks:
    - name: Ensure Docker is installed
      ansible.builtin.include_role:
        name: docker

  roles:
    - role: gitea
...
