proxmox_node                           = "pve"
debian_server_bookworm_packer_image_id = "999"
ubuntu_server_noble_packer_image_id    = "998"
vm_username                            = "mas"
ssh_public_key                         = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBapxTGEVjqrizkBt3kbJwwSJ1BlTgSOGuYSS//nR32T mas@TMV2"
openstack_cloud_name                   = "openstack"
