---
- name: Ensure nginx is at the latest version
  ansible.builtin.package:
    name: nginx
    state: present
  notify: restart nginx

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
...
