---
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    # build: ./
    restart: always
    ports:
      - '4100:4100'
    environment:
      TZ: Europe/Paris
      # CONFIG_PATH: /etc/puter
      PUID: 1000
      PGID: 1000
    volumes:
      - ${PWD}/config:/etc/puter
      - ${PWD}/data:/var/puter
...
