---
- name: Check if Helm is already installed
  command: helm version --short
  register: helm_installed
  ignore_errors: true
  changed_when: false

- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'
  when: helm_installed is failed or helm_installed.rc != 0

- name: Install Helm
  command: /tmp/get_helm.sh
  become: true
  when: helm_installed is failed or helm_installed.rc != 0
  register: helm_install_result
  changed_when: "'Helm' in helm_install_result.stdout"

- name: Verify Helm installation
  command: helm version --short
  register: helm_version
  changed_when: false

- name: Display Helm version
  debug:
    msg: "Helm {{ helm_version.stdout }} is installed"
...
