variable "name" {}
variable "desc" {}
variable "agent" {}
variable "target_node" {}
variable "tags" {}
variable "clone" {}
variable "full_clone" {}
variable "qemu_os" {}
variable "cores" {}
variable "sockets" {}
variable "cpu_type" {}
variable "memory" {}
variable "scsihw" {}
variable "bootdisk" {}
variable "cloudinit_storage" {}
variable "disk_storage" {}
variable "disk_size" {}
variable "iothread" {}
variable "replicate" {}
variable "network_id" {}
variable "network_model" {}
variable "network_bridge" {}
variable "ipconfig0" {}
variable "ciuser" {}
variable "sshkeys" {}
